############################ TYK ###########################
###
### TYK installation and configuration
###

- name: Add Tyk repo
  yum_repository:
    name: tyk_tyk-dashboard
    description: Elasticsearch repo
    baseurl: https://packagecloud.io/tyk/tyk-dashboard/el/7/$basearch
    repo_gpgcheck: 1
    gpgcheck: 1
    gpgkey:
      - http://keyserver.tyk.io/tyk.io.rpm.signing.key
      - https://packagecloud.io/tyk/tyk-dashboard/gpgkey
    enabled: 1

- name: Install prerequisites
  yum:
    name: python34
    state: present
